### ISSUE TITLE
Is there a way to attach stack traces to exceptions?

### ISSUE THREAD

**Issue by GavinRay97** [TietoEVRY/quarkus-resteasy-problem#227]
I'm curious if there is a way I can enable a stacktrace field in the message object, so that people who report errors can attach it?

Thank you =)

**Comment by lwitkowski** [comment]
Short answer: no, there's no way to expose stack traces in REST responses using this extension - and it's by design :)

Longer answer: exposing stack traces - in great majority of cases - in REST apis is not a good idea, especially for public apis in production. Developers should have easy access to backend logs where you can easily check the details of the exception.

IMO it's much better (and safer) to return correlation id (uuid) as additional field in the response:
```json
{
  "status": 500,
  "title": "Internal Server Error",
  "uuid": "d79f8cfa-ef5b-4501-a2c4-8f537c08ec0c"
}
```
And include this uuid in your logs so that you can find a specific stack trace based on the information your api client provides:
```
10:53:48 INFO [http-problem] (executor-thread-1) status=500, title="Internal Server Error", uuid="d79f8cfa-ef5b-4501-a2c4-8f537c08ec0c"
```
